INSERT INTO A_Ingredient (id,i_name) VALUES (1,'lettuce');
INSERT INTO A_Ingredient (id,i_name) VALUES (2,'tomatoes');
INSERT INTO A_Ingredient (id,i_name) VALUES (3,'cheese');
INSERT INTO A_Ingredient (id,i_name) VALUES (4,'beef');
INSERT INTO A_Ingredient (id,i_name) VALUES (5,'chicken');
INSERT INTO A_Ingredient (id,i_name) VALUES (6,'tortillas');
INSERT INTO A_Ingredient (id,i_name) VALUES (7,'peppers');
INSERT INTO A_Ingredient (id,i_name) VALUES (8,'sour cream');
INSERT INTO A_Ingredient (id,i_name) VALUES (9,'guacamole');
INSERT INTO A_Ingredient (id,i_name) VALUES (10,'beans');
